Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/12/2023
Var
// Seção de Declarações das variáveis 
   ola: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    Escreva ("Olá Mundo!")
    Leia (ola)

Fimalgoritmo